version: '3.3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    env_file: .env
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
        - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - 3306:$DB_PORT
      # Where our data will be persisted
    volumes:
      - mysql_db:/var/lib/mysql
# Names our volume
volumes:
  mysql_db:
      driver: local
