version: '3.3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    env_file: .env
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
        - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - 3306:$DB_PORT
    volumes:
      - mysql_db:/var/lib/mysql
      - ./db_webstore.sql:/docker-entrypoint-initdb.d/db_webstore.sql
# Names our volume
volumes:
  mysql_db:
      driver: local
